name: productivity_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.3
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/undraw_scrum_board_re_wk7v.svg
    - assets/images/undraw_learning_re_32qv.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
